// Export database functions
export {
  getDatabase,
  closeDatabase,
  getDatabasePath,
  getAirportByICAO,
  getAirportByIATA,
  getAirportsByCountry,
  getAirportsByState,
  getAirportsByCity,
  getAirportsByType,
  getAirportsWithTowers,
  getRunwaysByAirport,
  getOperationalData,
  getFrequencies,
  getFuelTypes,
  getInfrastructure,
  countAirports,
  type AirportRow,
  type RunwayRow,
  type OperationalRow,
  type FrequenciesRow,
  type InfrastructureRow,
} from "./db";
